//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/PlayerInputActionMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActionMap : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActionMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActionMap"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""04039d1f-a990-45ea-a903-87a8cd22e73b"",
            ""actions"": [
                {
                    ""name"": ""LeftArm"",
                    ""type"": ""Button"",
                    ""id"": ""54543c36-8c33-4bb9-a9dd-f64841192ed2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightArm"",
                    ""type"": ""Button"",
                    ""id"": ""a39660c6-99b7-4557-9eb8-5213eb7196e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ADS"",
                    ""type"": ""Button"",
                    ""id"": ""cdb687bb-ba43-47ab-a503-1702f4b5e67e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChestAbility"",
                    ""type"": ""Button"",
                    ""id"": ""d76e632a-f17a-49ba-8846-bc9a325c007d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LegAbility"",
                    ""type"": ""Button"",
                    ""id"": ""60f7c4d4-6337-4c05-84b4-f663cd5f06a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HeadDe/At_tachment"",
                    ""type"": ""Button"",
                    ""id"": ""429dee51-b266-4c6d-a2cd-7774dd7508e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""f4a5be9e-d9b2-4b87-a924-5dcde7f4763d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""3e23c3e0-244f-4938-9075-c5be9732ca2b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Head_PickUp"",
                    ""type"": ""Button"",
                    ""id"": ""240c5516-1f7f-4a05-9a8f-3393932bc043"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BodyPartSwap"",
                    ""type"": ""Value"",
                    ""id"": ""5450b343-7aa8-448f-bb85-d77cb4185e86"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HeadThrow"",
                    ""type"": ""Button"",
                    ""id"": ""3724ac8c-253d-4e6c-8548-e01090513a6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HandSwap"",
                    ""type"": ""Button"",
                    ""id"": ""ff207fe1-d2dc-486f-b946-d64a095159f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrintingChest"",
                    ""type"": ""Value"",
                    ""id"": ""47e733d6-0849-49ed-b5af-aaa5dc18a74f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""Value"",
                    ""id"": ""d51785ba-b0d7-4f6c-93c0-339d5ccd2c54"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jetpack"",
                    ""type"": ""Button"",
                    ""id"": ""60691166-41a9-4ac6-8056-b7b0920338d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left Click Holds"",
                    ""type"": ""Button"",
                    ""id"": ""0fb5f8d8-ee7d-4161-bb21-d804469b7ba7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right Click Holds"",
                    ""type"": ""Button"",
                    ""id"": ""b0022d5e-d558-46fc-b854-5ce421299b4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ae42cc2c-c38d-45fc-adae-04cf70a17148"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""LeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ee98c51-d776-452d-801d-eabbf869aea7"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""LeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""893e72ad-8965-424e-a592-894306a7a0c0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""RightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00ed4da8-00e8-455f-bafe-1183d7d462fd"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""RightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""432a5b70-4dba-42d9-847a-acf8970f85f6"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""ChestAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd76deb5-7ce1-4795-b8d0-36ecc1aac2e8"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""ChestAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0facec0d-31e6-480c-83bb-322bd6cafef2"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""LegAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd8eb3cc-8d27-401c-b1a6-874dcbd35f92"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""LegAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6aec715b-7440-451c-ba03-681b134c1f43"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""HeadDe/At_tachment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cac07e72-ec95-4660-b929-2d315d3ff519"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""HeadDe/At_tachment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""619ed6d1-26b2-4797-a3ee-885f84eb4b4b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25f8544e-3250-4372-99c9-3e062f68d6ec"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8a6b608-3e3c-4c9c-8543-7885fd6e5433"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Head_PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c69cd003-33f1-4f53-8de6-91ac612686be"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""HeadThrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f568f7a-ee34-445c-bf5d-ee71c26058ab"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""HeadThrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7550a4ce-ce3b-47f4-8280-417558533702"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""HandSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""a98a5cf5-85a0-410e-810c-f9a16c6fa13a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bc34f1b5-6410-48c4-ac01-0a5fbe366fe7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""09bf4212-353b-4e68-b82c-1cd959289ba1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a4fcd95a-1724-4b37-bd49-17f0d7e5c3f5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9fe79865-8ea0-4776-a16c-237f275c82d5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow"",
                    ""id"": ""a0ed0fe0-0818-47b2-b4cc-0925f728101c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4c977604-0619-4d3c-95c1-719bcbf83357"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4ceeec3f-6714-426f-917d-dcbe2ebb2102"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""51a44a98-b2ea-464f-ac03-dbd41f07450f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9b59e729-5cdc-4b43-b84d-25d2fe5415b0"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""197fb89b-a2a5-49cb-9626-3fc80f8bee0a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""GamePad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e455ee47-c367-48cd-a1f1-5dc2241fe1bb"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcaa2e9f-43fe-4269-a707-8f821786528a"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7e656e1d-e981-440f-be8c-0eaf832e2c3a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BodyPartSwap"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8a79b5ed-2541-4703-a2ae-404747971d86"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""BodyPartSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dbddd95f-31ab-4525-9fa8-74a22b6ce14b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""BodyPartSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""19a83a55-ce86-4269-aec6-4b6d9a1deb8e"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""BodyPartSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3bfdeeb0-f578-4436-a86e-f410a0cbad24"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""BodyPartSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7e6eb272-6d04-4f36-a67b-16630ee16a8d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BodyPartSwap"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2b7cf6c8-69b4-4997-a5c6-3d9d9865327f"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""BodyPartSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""327537bf-3297-44b3-ae01-1b880e46dc02"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""BodyPartSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b9a5bf8e-94fc-45ff-8fbf-f6993e61ca1d"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""BodyPartSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c1b3f1b2-775c-4c9d-9a58-17d33843b70d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""BodyPartSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8e25c9ff-4188-46da-95c5-62f774cc1248"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""Jetpack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a9ff2f7-aa1b-4b57-8455-35adee629239"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Jetpack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""09f51592-3d8d-43b4-ba92-2a0484d745d0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrintingChest"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cd1ca456-6374-4574-8249-78beb0b0c391"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrintingChest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""59001798-b00c-49be-ba01-2bb90a6b7269"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrintingChest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""809c3760-1bf3-444a-9211-36d3c0a58b0d"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrintingChest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""89d92375-3ffb-4b36-86c3-bb0b31ee1ca6"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrintingChest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""06178428-9a45-4d18-aac0-d80bfbcdbdb0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left Click Holds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9da90caa-e29b-4f76-bc75-9e5c3ce76cbf"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Hold(pressPoint=0.5)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Click Holds"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb13e2b7-fe0d-42b3-b9e9-aae718465728"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard_Mouse"",
                    ""action"": ""ADS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard_Mouse"",
            ""bindingGroup"": ""Keyboard_Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""GamePad"",
            ""bindingGroup"": ""GamePad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_LeftArm = m_Player.FindAction("LeftArm", throwIfNotFound: true);
        m_Player_RightArm = m_Player.FindAction("RightArm", throwIfNotFound: true);
        m_Player_ADS = m_Player.FindAction("ADS", throwIfNotFound: true);
        m_Player_ChestAbility = m_Player.FindAction("ChestAbility", throwIfNotFound: true);
        m_Player_LegAbility = m_Player.FindAction("LegAbility", throwIfNotFound: true);
        m_Player_HeadDeAt_tachment = m_Player.FindAction("HeadDe/At_tachment", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Head_PickUp = m_Player.FindAction("Head_PickUp", throwIfNotFound: true);
        m_Player_BodyPartSwap = m_Player.FindAction("BodyPartSwap", throwIfNotFound: true);
        m_Player_HeadThrow = m_Player.FindAction("HeadThrow", throwIfNotFound: true);
        m_Player_HandSwap = m_Player.FindAction("HandSwap", throwIfNotFound: true);
        m_Player_PrintingChest = m_Player.FindAction("PrintingChest", throwIfNotFound: true);
        m_Player_Camera = m_Player.FindAction("Camera", throwIfNotFound: true);
        m_Player_Jetpack = m_Player.FindAction("Jetpack", throwIfNotFound: true);
        m_Player_LeftClickHolds = m_Player.FindAction("Left Click Holds", throwIfNotFound: true);
        m_Player_RightClickHolds = m_Player.FindAction("Right Click Holds", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_LeftArm;
    private readonly InputAction m_Player_RightArm;
    private readonly InputAction m_Player_ADS;
    private readonly InputAction m_Player_ChestAbility;
    private readonly InputAction m_Player_LegAbility;
    private readonly InputAction m_Player_HeadDeAt_tachment;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Head_PickUp;
    private readonly InputAction m_Player_BodyPartSwap;
    private readonly InputAction m_Player_HeadThrow;
    private readonly InputAction m_Player_HandSwap;
    private readonly InputAction m_Player_PrintingChest;
    private readonly InputAction m_Player_Camera;
    private readonly InputAction m_Player_Jetpack;
    private readonly InputAction m_Player_LeftClickHolds;
    private readonly InputAction m_Player_RightClickHolds;
    public struct PlayerActions
    {
        private @PlayerInputActionMap m_Wrapper;
        public PlayerActions(@PlayerInputActionMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftArm => m_Wrapper.m_Player_LeftArm;
        public InputAction @RightArm => m_Wrapper.m_Player_RightArm;
        public InputAction @ADS => m_Wrapper.m_Player_ADS;
        public InputAction @ChestAbility => m_Wrapper.m_Player_ChestAbility;
        public InputAction @LegAbility => m_Wrapper.m_Player_LegAbility;
        public InputAction @HeadDeAt_tachment => m_Wrapper.m_Player_HeadDeAt_tachment;
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Head_PickUp => m_Wrapper.m_Player_Head_PickUp;
        public InputAction @BodyPartSwap => m_Wrapper.m_Player_BodyPartSwap;
        public InputAction @HeadThrow => m_Wrapper.m_Player_HeadThrow;
        public InputAction @HandSwap => m_Wrapper.m_Player_HandSwap;
        public InputAction @PrintingChest => m_Wrapper.m_Player_PrintingChest;
        public InputAction @Camera => m_Wrapper.m_Player_Camera;
        public InputAction @Jetpack => m_Wrapper.m_Player_Jetpack;
        public InputAction @LeftClickHolds => m_Wrapper.m_Player_LeftClickHolds;
        public InputAction @RightClickHolds => m_Wrapper.m_Player_RightClickHolds;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @LeftArm.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftArm;
                @LeftArm.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftArm;
                @LeftArm.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftArm;
                @RightArm.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightArm;
                @RightArm.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightArm;
                @RightArm.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightArm;
                @ADS.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnADS;
                @ADS.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnADS;
                @ADS.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnADS;
                @ChestAbility.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChestAbility;
                @ChestAbility.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChestAbility;
                @ChestAbility.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChestAbility;
                @LegAbility.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLegAbility;
                @LegAbility.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLegAbility;
                @LegAbility.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLegAbility;
                @HeadDeAt_tachment.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeadDeAt_tachment;
                @HeadDeAt_tachment.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeadDeAt_tachment;
                @HeadDeAt_tachment.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeadDeAt_tachment;
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Head_PickUp.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHead_PickUp;
                @Head_PickUp.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHead_PickUp;
                @Head_PickUp.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHead_PickUp;
                @BodyPartSwap.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBodyPartSwap;
                @BodyPartSwap.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBodyPartSwap;
                @BodyPartSwap.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBodyPartSwap;
                @HeadThrow.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeadThrow;
                @HeadThrow.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeadThrow;
                @HeadThrow.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeadThrow;
                @HandSwap.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHandSwap;
                @HandSwap.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHandSwap;
                @HandSwap.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHandSwap;
                @PrintingChest.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPrintingChest;
                @PrintingChest.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPrintingChest;
                @PrintingChest.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPrintingChest;
                @Camera.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCamera;
                @Camera.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCamera;
                @Camera.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCamera;
                @Jetpack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJetpack;
                @Jetpack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJetpack;
                @Jetpack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJetpack;
                @LeftClickHolds.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftClickHolds;
                @LeftClickHolds.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftClickHolds;
                @LeftClickHolds.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftClickHolds;
                @RightClickHolds.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightClickHolds;
                @RightClickHolds.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightClickHolds;
                @RightClickHolds.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightClickHolds;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LeftArm.started += instance.OnLeftArm;
                @LeftArm.performed += instance.OnLeftArm;
                @LeftArm.canceled += instance.OnLeftArm;
                @RightArm.started += instance.OnRightArm;
                @RightArm.performed += instance.OnRightArm;
                @RightArm.canceled += instance.OnRightArm;
                @ADS.started += instance.OnADS;
                @ADS.performed += instance.OnADS;
                @ADS.canceled += instance.OnADS;
                @ChestAbility.started += instance.OnChestAbility;
                @ChestAbility.performed += instance.OnChestAbility;
                @ChestAbility.canceled += instance.OnChestAbility;
                @LegAbility.started += instance.OnLegAbility;
                @LegAbility.performed += instance.OnLegAbility;
                @LegAbility.canceled += instance.OnLegAbility;
                @HeadDeAt_tachment.started += instance.OnHeadDeAt_tachment;
                @HeadDeAt_tachment.performed += instance.OnHeadDeAt_tachment;
                @HeadDeAt_tachment.canceled += instance.OnHeadDeAt_tachment;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Head_PickUp.started += instance.OnHead_PickUp;
                @Head_PickUp.performed += instance.OnHead_PickUp;
                @Head_PickUp.canceled += instance.OnHead_PickUp;
                @BodyPartSwap.started += instance.OnBodyPartSwap;
                @BodyPartSwap.performed += instance.OnBodyPartSwap;
                @BodyPartSwap.canceled += instance.OnBodyPartSwap;
                @HeadThrow.started += instance.OnHeadThrow;
                @HeadThrow.performed += instance.OnHeadThrow;
                @HeadThrow.canceled += instance.OnHeadThrow;
                @HandSwap.started += instance.OnHandSwap;
                @HandSwap.performed += instance.OnHandSwap;
                @HandSwap.canceled += instance.OnHandSwap;
                @PrintingChest.started += instance.OnPrintingChest;
                @PrintingChest.performed += instance.OnPrintingChest;
                @PrintingChest.canceled += instance.OnPrintingChest;
                @Camera.started += instance.OnCamera;
                @Camera.performed += instance.OnCamera;
                @Camera.canceled += instance.OnCamera;
                @Jetpack.started += instance.OnJetpack;
                @Jetpack.performed += instance.OnJetpack;
                @Jetpack.canceled += instance.OnJetpack;
                @LeftClickHolds.started += instance.OnLeftClickHolds;
                @LeftClickHolds.performed += instance.OnLeftClickHolds;
                @LeftClickHolds.canceled += instance.OnLeftClickHolds;
                @RightClickHolds.started += instance.OnRightClickHolds;
                @RightClickHolds.performed += instance.OnRightClickHolds;
                @RightClickHolds.canceled += instance.OnRightClickHolds;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_Keyboard_MouseSchemeIndex = -1;
    public InputControlScheme Keyboard_MouseScheme
    {
        get
        {
            if (m_Keyboard_MouseSchemeIndex == -1) m_Keyboard_MouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard_Mouse");
            return asset.controlSchemes[m_Keyboard_MouseSchemeIndex];
        }
    }
    private int m_GamePadSchemeIndex = -1;
    public InputControlScheme GamePadScheme
    {
        get
        {
            if (m_GamePadSchemeIndex == -1) m_GamePadSchemeIndex = asset.FindControlSchemeIndex("GamePad");
            return asset.controlSchemes[m_GamePadSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnLeftArm(InputAction.CallbackContext context);
        void OnRightArm(InputAction.CallbackContext context);
        void OnADS(InputAction.CallbackContext context);
        void OnChestAbility(InputAction.CallbackContext context);
        void OnLegAbility(InputAction.CallbackContext context);
        void OnHeadDeAt_tachment(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnHead_PickUp(InputAction.CallbackContext context);
        void OnBodyPartSwap(InputAction.CallbackContext context);
        void OnHeadThrow(InputAction.CallbackContext context);
        void OnHandSwap(InputAction.CallbackContext context);
        void OnPrintingChest(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnJetpack(InputAction.CallbackContext context);
        void OnLeftClickHolds(InputAction.CallbackContext context);
        void OnRightClickHolds(InputAction.CallbackContext context);
    }
}
